import type { Metadata } from "next";
import "@/app/global.css";
import SideBar from "@/componentes/global/SideBar";
import SessionProviderWrapper from "@/componentes/global/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <>
      <SessionProviderWrapper>
        <SideBar />
        <>
          {children}
          {modal}
        </>
      </SessionProviderWrapper>
    </>
  );
}
